# Generated by Django 5.2.14 on 2026-06-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Riesgo',
            fields=[
                ('id_nivel_de_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_riesgo', models.CharField(default='Bajo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=250)),
                ('fechadevencimiento', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('fechadeingreso', models.DateField()),
                ('fechadedispensa', models.DateField(blank=True, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='medicamento/qr/')),
                ('codigo_barras', models.BigIntegerField()),
                ('refrigeracion', models.CharField(max_length=200)),
                ('cant_stock', models.IntegerField()),
                ('id_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.deposito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.estado')),
                ('id_nivel_de_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.nivel_riesgo')),
            ],
        ),
    ]
